### ISSUE TITLE
手动是正常的，但用 ptrsx-dumper 都是报 Error

### ISSUE THREAD

**Issue by bbingz** [kekeimiku/dumpkey#2]
~/Downloads/ptrsx-aarch64-apple-darwin
❯ ./ptrsx-dumper test --pid $(pgrep WeChat |head -1) --path "WeChat+0x53af490->0->8->8->16->32->8->8->64->8->0->0" -n 32
Error: ReadMemory(1)

**Comment by kekeimiku** [comment]
你确定是对应的版本吗

**Comment by bbingz** [comment]
是对应的版本
![CleanShot 2023-07-11 at 17 09 52@2x](https://github.com/kekeimiku/dumpkey/assets/11211020/e99d3829-2cdd-41b8-ba3a-7029d616ed32)

**Comment by bbingz** [comment]
有macOS上的查找基址教程吗？求教。

**Comment by bbingz** [comment]
按你的 B 站视频猜的，只能找到这样的，求指点
![CleanShot 2023-07-11 at 19 50 07@2x](https://github.com/kekeimiku/dumpkey/assets/11211020/bb5d11ea-7ba1-4526-8cf5-4b63303274cd)

**Comment by kekeimiku** [comment]
> 按你的 B 站视频猜的，只能找到这样的，求指点 ![CleanShot 2023-07-11 at 19 50 07@2x](https://user-images.githubusercontent.com/11211020/252654567-bb5d11ea-7ba1-4526-8cf5-4b63303274cd.png)

depth 设置 11 , offset 设置 0:200 应该就可以。 然后对比两次或者三次的扫描结果，找出每次都存在的那个指针链就可以了。

**Comment by bbingz** [comment]
谢谢，可是 depth 设置 11，出来的数据很大，有3-4GB，然后 diff 出来的数据也很大，这个正常吗？

**Comment by kekeimiku** [comment]
> 谢谢，可是 depth 设置 11，出来的数据很大，有3-4GB，然后 diff 出来的数据也很大，这个正常吗？

正常，数据有多少取决于设置了多大的depth和offset，设置的越大扫描速度越慢结果越多。

**Comment by bbingz** [comment]
1. vmmap 出 load address;
2.dump 下相关pid 的内存；
3.用 load address 在2当中的查找，11 depth，偏移 0:200
4.转成 txt
5.多次 txt 比对 diff 出相同数据
6.猜？

对不？ 试了几次找不到。 🤦🏻‍♂️

**Comment by kekeimiku** [comment]
> 1. vmmap 出 load address;
>    2.dump 下相关pid 的内存；
>    3.用 load address 在2当中的查找，11 depth，偏移 0:200
>    4.转成 txt
>    5.多次 txt 比对 diff 出相同数据
>    6.猜？
> 
> 对不？ 试了几次找不到。 🤦🏻‍♂️

我怀疑你使用方式有误，建议邮件你发个微信我加你看看，你只需要发我dump文件。

kekelanact@gmail.com

**Comment by bbingz** [comment]
谢谢，已发邮件。
