### ISSUE TITLE
Error: Error("OpenProcess, (os/kern) failure. code: 5")

### ISSUE THREAD

**Issue by 526462712** [kekeimiku/dumpkey#3]
刚接触macos没多久，请问提示这个要怎么解决呢？
Error: Error("OpenProcess, (os/kern) failure. code: 5")
<img width="585" alt="image" src="https://github.com/kekeimiku/dumpkey/assets/34618949/643764ad-1a95-4c67-ac5c-1936dbd374ba">
<img width="869" alt="image" src="https://github.com/kekeimiku/dumpkey/assets/34618949/a19c7b7b-87a2-4e33-bdb7-51febfb33781">
<img width="550" alt="image" src="https://github.com/kekeimiku/dumpkey/assets/34618949/0b84e2a2-7b4b-4fc5-9bf6-59ed8da19f1b">
系统版本是sonoma 14.0 Beta版(23A5337a)
感谢作者！！

**Comment by kekeimiku** [comment]
可能需要对微信重签名，关闭微信 运行 `sudo codesign --sign - --force --deep /Applications/WeChat.app` 命令，然后重新打开。

或者关闭sip

**Comment by paulzhn** [comment]
建议把关闭sip写到readme里
