### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by amasawa** [kekeimiku/dumpkey#4]
`
/ptrsx-dumper test --pid $(pgrep WeChat |head -1) --path "WeChat+0x4C58BC0->0->8->8->16->32->8->8->64->8->0->0" -n 32
Error parsing option '--pid' with value '--path': invalid digit found in string
Run ptrsx-dumper --help for more information.
`

**Comment by kekeimiku** [comment]
有没有完整截图，这看起来很奇怪。

**Comment by kekeimiku** [comment]
> 微信打开时候报
> <img alt="Screen Shot 2023-09-08 at 19 12 00" width="639" src="https://user-images.githubusercontent.com/27271254/266562158-7b21ca66-8697-4197-831d-3af2ee14a852.png">

是不是没有登陆进微信

**Comment by amasawa** [comment]
已经登录进了，版本也对

**Comment by kekeimiku** [comment]
> 已经登录进了，版本也对

![image](https://github.com/kekeimiku/dumpkey/assets/36557882/f6eecb83-2a55-4100-a613-b43a5f9518b7)

不知道什么原因了，这个报错应该只会在版本不对或者没有登陆的情况下出现。

**Comment by wangshug** [comment]
我也遇到了，brew 安装的wechat的版本Version 3.8.2 (27317)
<img width="408" alt="Screenshot 2023-09-09 at 17 03 21" src="https://github.com/kekeimiku/dumpkey/assets/1720863/fea944a5-eadb-40ef-a044-7dc3b1bad19c">

**Comment by kekeimiku** [comment]
> 我也遇到了，brew 安装的wechat的版本Version 3.8.2 (27317)
> <img alt="Screenshot 2023-09-09 at 17 03 21" width="408" src="https://user-images.githubusercontent.com/1720863/266771243-fea944a5-eadb-40ef-a044-7dc3b1bad19c.png">

还没有支持这个版本，晚上我会看看。

**Comment by kekeimiku** [comment]
> 我也遇到了，brew 安装的wechat的版本Version 3.8.2 (27317)
> <img alt="Screenshot 2023-09-09 at 17 03 21" width="408" src="https://user-images.githubusercontent.com/1720863/266771243-fea944a5-eadb-40ef-a044-7dc3b1bad19c.png">

我刚刚用brew下载了一个和你一样的版本。

你试试这个命令：
```
ptrsx-dumper test -p $(pgrep WeChat |head -1) --path "WeChat+0x4C19580->0->8->8->16->32->8->8->64->8->0->0" -n 32
```

**Comment by amasawa** [comment]
重新检查了一下版本Version 3.8.2 (27317），尝试之后还是有这个问题
<img width="505" alt="Screen Shot 2023-09-09 at 21 36 02" src="https://github.com/kekeimiku/dumpkey/assets/27271254/785f900a-097f-42a2-b9d8-2d349461a6f7">
<img width="933" alt="Screen Shot 2023-09-09 at 21 36 35" src="https://github.com/kekeimiku/dumpkey/assets/27271254/c7bd3c83-3e5e-42ef-9a5d-89afca560d63">
另外试了一下官网Version 3.8.3 (27318),还是有问题
![Screen Shot 2023-09-09 at 21 42 35](https://github.com/kekeimiku/dumpkey/assets/27271254/f133d514-d851-4f88-9bb7-dd27aa21c6fb)
<img width="642" alt="Screen Shot 2023-09-09 at 21 43 36" src="https://github.com/kekeimiku/dumpkey/assets/27271254/3a2bda93-d2fa-4c1c-88ed-d5fa98e3f6ae">

**Comment by kekeimiku** [comment]
> 重新检查了一下版本Version 3.8.2 (27317），尝试之后还是有这个问题
> <img alt="Screen Shot 2023-09-09 at 21 36 02" width="505" src="https://user-images.githubusercontent.com/27271254/266778012-785f900a-097f-42a2-b9d8-2d349461a6f7.png">
> <img alt="Screen Shot 2023-09-09 at 21 36 35" width="933" src="https://user-images.githubusercontent.com/27271254/266778025-c7bd3c83-3e5e-42ef-9a5d-89afca560d63.png">
> 另外试了一下官网Version 3.8.3 (27318),还是有问题
> ![Screen Shot 2023-09-09 at 21 42 35](https://user-images.githubusercontent.com/27271254/266778318-f133d514-d851-4f88-9bb7-dd27aa21c6fb.png)
> <img alt="Screen Shot 2023-09-09 at 21 43 36" width="642" src="https://user-images.githubusercontent.com/27271254/266778363-3a2bda93-d2fa-4c1c-88ed-d5fa98e3f6ae.png">

这个报错`OpenProcess(5)`一般是没有权限，需要对微信重签名，尝试关闭微信 运行 `sudo codesign --sign - --force --deep /Applications/WeChat.app` 命令，然后重新打开，或者关闭sip

**Comment by amasawa** [comment]
对已经关闭运行了，主要是 Error parsing option(感谢巨巨）

**Comment by kekeimiku** [comment]
> 

能获取到key了吗，`Error parsing option ` 是因为没有打开微信的时候 `pgrep WeChat |head -1` 获取pid，返回的是空字符串，所以命令行解析报错了。

**Comment by wangshug** [comment]
> > 我也遇到了，brew 安装的wechat的版本Version 3.8.2 (27317)
> > <img alt="Screenshot 2023-09-09 at 17 03 21" width="408" src="https://user-images.githubusercontent.com/1720863/266771243-fea944a5-eadb-40ef-a044-7dc3b1bad19c.png">
> 
> 我刚刚用brew下载了一个和你一样的版本。
> 
> 你试试这个命令：
> 
> ```
> ptrsx-dumper test -p $(pgrep WeChat |head -1) --path "WeChat+0x4C19580->0->8->8->16->32->8->8->64->8->0->0" -n 32
> ```

这个可以了，🤗

**Comment by amasawa** [comment]
> 

Done!

**Comment by amasawa** [comment]
> > 
> 
> 能获取到key了吗，`Error parsing option ` 是因为没有打开微信的时候 `pgrep WeChat |head -1` 获取pid，返回的是空字符串，所以命令行解析报错了。

Done! thx!

**Comment by amasawa** [comment]
> > 
> 
> 能获取到key了吗，`Error parsing option ` 是因为没有打开微信的时候 `pgrep WeChat |head -1` 获取pid，返回的是空字符串，所以命令行解析报错了。

Done! Thx!
